# -*- coding: utf-8 -*-
"""ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvWEgOYAZCZt2o4IIrsWViZDABTiY0Ws
"""

import pandas as pd
df = pd.read_csv('/content/Salary_Data.csv')
df.info()

df.isnull().sum()

for col in ['Age', 'Years of Experience', 'Salary']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

for col in ['Gender', 'Education Level', 'Job Title']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

# Verify that there are no more null values
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to categorical columns
for col in ['Gender', 'Education Level', 'Job Title']:
    df[col] = le.fit_transform(df[col])

# Display the first few rows of the updated DataFrame
display(df.head())

# Save the fitted LabelEncoders for future use in the Streamlit app
import joblib

# Create a dictionary to store the encoders
label_encoders = {}
for col in ['Gender', 'Education Level', 'Job Title']:
    # Re-initialize and fit LabelEncoder for each column to capture the exact state
    # This is done because the original 'le' object was overwritten in the loop
    le_temp = LabelEncoder()
    le_temp.fit(df[col]) # Fit to the entire column to ensure all categories are encoded
    label_encoders[col] = le_temp

    # Display the mapping for verification
    print(f"LabelEncoder mapping for {col}:")
    for i, item in enumerate(le_temp.classes_):
        print(f"  {item} -> {i}")

# Save the dictionary of fitted encoders
joblib.dump(label_encoders, 'label_encoders.pkl')
print("Label encoders saved to 'label_encoders.pkl'")

from google.colab import files
files.download('label_encoders.pkl')

# Separate independent and dependent variables
X = df.drop('Salary', axis=1)
y = df['Salary']

print("Independent variables (X):")
display(X.head())

print("\nDependent variable (y):")
display(y.head())

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""### Linear Regression Model"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the Linear Regression model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr = linear_reg_model.predict(X_test)

# Evaluate the model
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Linear Regression - Mean Squared Error: {mse_lr:.2f}")
print(f"Linear Regression - R-squared: {r2_lr:.2f}")

"""### Decision Tree Regressor Model"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dt = decision_tree_model.predict(X_test)

# Evaluate the model
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree Regressor - Mean Squared Error: {mse_dt:.2f}")
print(f"Decision Tree Regressor - R-squared: {r2_dt:.2f}")

"""### Random Forest Regressor Model"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the Random Forest Regressor model
random_forest_model = RandomForestRegressor(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = random_forest_model.predict(X_test)

# Evaluate the model
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest Regressor - Mean Squared Error: {mse_rf:.2f}")
print(f"Random Forest Regressor - R-squared: {r2_rf:.2f}")

"""### Support Vector Machine (SVR) Model"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# SVMs are sensitive to feature scaling, so we'll scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train the SVR model
# Using a linear kernel for simplicity, can be changed to rbf etc.
svr_model = SVR(kernel='linear')
svr_model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test set
y_pred_svr = svr_model.predict(X_test_scaled)

# Evaluate the model
mse_svr = mean_squared_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f"Support Vector Regressor - Mean Squared Error: {mse_svr:.2f}")
print(f"Support Vector Regressor - R-squared: {r2_svr:.2f}")

"""### K-Nearest Neighbors (KNN) Regressor Model"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the K-Nearest Neighbors Regressor model
# Using default n_neighbors=5, can be tuned
knn_model = KNeighborsRegressor(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mse_knn = mean_squared_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"K-Nearest Neighbors Regressor - Mean Squared Error: {mse_knn:.2f}")
print(f"K-Nearest Neighbors Regressor - R-squared: {r2_knn:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
metrics_data = {
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVR', 'KNN'],
    'MSE': [mse_lr, mse_dt, mse_rf, mse_svr, mse_knn],
    'R-squared': [r2_lr, r2_dt, r2_rf, r2_svr, r2_knn]
}

df_metrics = pd.DataFrame(metrics_data)

# Create subplots for MSE and R-squared
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot MSE
sns.barplot(x='Model', y='MSE', data=df_metrics, ax=axes[0], palette='viridis', hue='Model', legend=False)
axes[0].set_title('Model Performance: Mean Squared Error')
axes[0].set_ylabel('Mean Squared Error')
axes[0].ticklabel_format(style='plain', axis='y') # Prevent scientific notation
axes[0].set_xticks(axes[0].get_xticks())
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=45, ha='right')

# Plot R-squared
sns.barplot(x='Model', y='R-squared', data=df_metrics, ax=axes[1], palette='plasma', hue='Model', legend=False)
axes[1].set_title('Model Performance: R-squared')
axes[1].set_ylabel('R-squared')
axes[1].set_ylim(0, 1) # R-squared typically ranges from 0 to 1
axes[1].set_xticks(axes[1].get_xticks())
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=45, ha='right')

plt.tight_layout()
plt.show()

import pickle

# Assuming random_forest_model is the best model based on previous evaluation
# Save the best model to a file
with open('best_model.pkl', 'wb') as file:
    pickle.dump(random_forest_model, file)

print("Best model (Random Forest Regressor) saved as best_model.pkl")

from google.colab import files
files.download('best_model.pkl')

"""### Streamlit Deployment

To deploy your model with Streamlit, you'll need to create a Python file (e.g., `app.py`) containing the application code. This application will load your trained model and the `LabelEncoder` objects, provide an interface for users to input features, and display salary predictions.
"""

streamlit_app_code = '''
import streamlit as st
import pandas as pd
import joblib
import os

# --- Load the trained model and label encoders ---
# Ensure these files are in the same directory as your Streamlit app.py or accessible via path
model_path = 'best_model.pkl'
encoders_path = 'label_encoders.pkl'

if not os.path.exists(model_path):
    st.error(f"Error: Model file not found at {model_path}")
    st.stop()

if not os.path.exists(encoders_path):
    st.error(f"Error: Label encoders file not found at {encoders_path}")
    st.stop()

try:
    model = joblib.load(model_path)
    label_encoders = joblib.load(encoders_path)
except Exception as e:
    st.error(f"Error loading model or label encoders: {e}")
    st.stop()

# --- Streamlit UI ---
st.title('Salary Prediction App')
st.write('Enter the details below to predict the salary.')

# Input fields
age = st.slider('Age', 18, 65, 30)
gender = st.selectbox('Gender', label_encoders['Gender'].classes_)
education_level = st.selectbox('Education Level', label_encoders['Education Level'].classes_)
job_title = st.selectbox('Job Title', label_encoders['Job Title'].classes_)
years_of_experience = st.slider('Years of Experience', 0.0, 40.0, 5.0, 0.5)

# Predict button
if st.button('Predict Salary'):
    # Create a DataFrame for the input features
    input_df = pd.DataFrame({
        'Age': [age],
        'Gender': [gender],
        'Education Level': [education_level],
        'Job Title': [job_title],
        'Years of Experience': [years_of_experience]
    })

    # Apply Label Encoding to categorical features using the loaded encoders
    for col in ['Gender', 'Education Level', 'Job Title']:
        if col in input_df.columns and col in label_encoders:
            try:
                input_df[col] = label_encoders[col].transform(input_df[col])
            except ValueError as e:
                st.error(f"Error encoding '{col}': {e}. Please ensure the selected category is valid.")
                st.stop()

    # Make prediction
    try:
        prediction = model.predict(input_df)
        st.success(f'Predicted Salary: ${prediction[0]:,.2f}')
    except Exception as e:
        st.error(f"Error making prediction: {e}")
'''

print("Save the following code as `app.py`:")
print("```python")
print(streamlit_app_code)
print("```")

"""### How to run the Streamlit App:

1.  **Install Streamlit:** If you don't have it installed, run `pip install streamlit scikit-learn pandas joblib`. You might also need to install the specific versions of `scikit-learn` and `pandas` that were used when training your model to avoid compatibility issues.
2.  **Save the files:** Save the `best_model.pkl`, `label_encoders.pkl`, and the `app.py` code (provided above) in the same directory.
3.  **Run the app:** Open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run the command: `streamlit run app.py`

This will open the Streamlit application in your web browser, allowing you to interact with your deployed salary prediction model.
"""

!pip freeze > requirements.txt
print("requirements.txt generated successfully!")

from google.colab import files
files.download('requirements.txt')



